---
name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.17, 1.18, 1.19]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goVer }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Make
        run: make
