---
name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v -coverprofile="coverage.out" ./...
      - run: go tool cover -func="coverage.out"
      - uses: vladopajic/go-test-coverage@v2.16.1
        with:
          config: ".github/testcoverage.yml"
