---
name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ["1.20", "1.21"]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goVer }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Make
        run: make
      - name: Check test coverage threshold
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/testcoverage.yml
